name: request_notification_permission_page
description: "Request Notification Permission Sample Page"
#publish_to: 'none'
repository: https://github.com/juneview-songdo/request_notification_permission_page

version: 1.0.4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more: #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/request_notification_permission_page/
  uses-material-design: true